@startuml

title Diagrama de Atividade - Criar Tarefa

start
:Usuário seleciona a opção para criar uma nova tarefa;
:O sistema apresenta uma forma para a entrada dos detalhes da tarefa;
:Usuário entra com o título, descrição, data de conclusão prevista e prioridade da tarefa;
if (Validação das informações) then (Sucesso)
    :O sistema cria a tarefa;
    stop
else (Falha)
    :O sistema informa o usuário sobre os erros;
    :O sistema pede por correções;
endif
stop

@enduml
