@startuml

title Diagrama de Atividade - Logar-se no sistema com Captcha

start
:Usuário entra com o email, senha e resolve o captcha;
if (Validação das informações e resposta do captcha?) then (Sim)
    :O sistema autentica o usuário;
    stop
else (Não)
    :O sistema informa o usuário sobre os erros e nega a autenticação;
endif
stop

@enduml
